products.importer.plugin.*:
  type: mapping
  label: "Plugin configuration"

plugin_configuration:
  type: products.importer.plugin.[%parent.plugin]

products.importer.plugin.json:
  type: mapping
  label: Plugin configuration for the Json importer plugin
  mapping:
    url:
      type: uri
      label: Uri

views.field.product_importer:
  type: views_field
  label: "Product Importer"
  mapping:
    importer:
      type: string
      label: "Which importer label to use: entity or plugin"
