<?php

/**
 * Use theme_hook()
 */
function hero_module_theme($existing, $type, $theme, $path)
{
    return [
        'hero_list' => [
            'variables' => [
                'items' => [],
                'title' => ''
            ]
        ],
        'exercise' => [
            'variables' => [
                'items' => [],
                'title' => ''
            ]
        ],
        'clock' => [
            'variables' => [
                'items' => '',
                'title' => '',
                'target' => ''
            ]
        ]
    ];
}
